
# Various constants used within the GUI
ERROR_HIGHLIGHT_COLOUR = '#FFB0B0'
SEQS_MIN, SEQS_MAX = 2, 26
EXPRS_MIN, EXPRS_MAX = 1, 300
ZERO_BOUND = 1e-7
HOVER_COLOUR = '#F1F5FF'
SELECTED_COLOUR = '#D9E5EF'

